/*
CREATE TABLE profiles (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    website VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE profiles_contact (
    id SERIAL PRIMARY KEY,
    profile_id INTEGER REFERENCES profiles(id) ON DELETE CASCADE,
    phone VARCHAR(20),
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(profile_id)
);

CREATE TABLE summaries (
    id SERIAL PRIMARY KEY,
    profile_id INTEGER REFERENCES profiles(id) ON DELETE CASCADE,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE experiences (
    id SERIAL PRIMARY KEY,
    profile_id INTEGER REFERENCES profiles(id) ON DELETE CASCADE,
    company VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE, -- NULL si es "actualidad"
    url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE responsibilities (
    id SERIAL PRIMARY KEY,
    experience_id INTEGER REFERENCES experiences(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE education_types (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE education (
    id SERIAL PRIMARY KEY,
    profile_id INTEGER REFERENCES profiles(id) ON DELETE CASCADE,
    type_id INTEGER REFERENCES education_types(id),
    start_date DATE,
    end_date DATE,
    url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE skill_types (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE skills (
    id SERIAL PRIMARY KEY,
    profile_id INTEGER REFERENCES profiles(id) ON DELETE CASCADE,
    type_id INTEGER REFERENCES skill_types(id),
    created_at TIMESTAMPTZ DEFAULT now()
);
*/

-- Tablas Data Base (Metadatos y Estructura)

-- 1. PROFILES

CREATE TABLE profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    website VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. PROFILES_CONTACT

CREATE TABLE profiles_contact (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX idx_profiles_contact_profile_id ON profiles_contact(profile_id);
CREATE UNIQUE INDEX idx_profiles_contact_email ON profiles_contact(email);
ALTER TABLE profiles_contact ADD CONSTRAINT fk_contact_profile 
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- 3. SUMMARIES

CREATE TABLE summaries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER NOT NULL,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE summaries ADD CONSTRAINT fk_summaries_profile 
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- 4. EXPERIENCES

CREATE TABLE experiences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER NOT NULL,
    company VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE experiences ADD CONSTRAINT fk_experiences_profile 
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- 5. RESPONSIBILITIES

CREATE TABLE responsibilities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experience_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE responsibilities ADD CONSTRAINT fk_responsibilities_experience 
    FOREIGN KEY (experience_id) REFERENCES experiences(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- 6. EDUCATION_TYPES / SKILL_TYPES

CREATE TABLE education_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX idx_education_types_slug ON education_types(slug);

CREATE TABLE skill_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX idx_skill_types_slug ON skill_types(slug);

-- 7. EDUCATION / SKILLS

CREATE TABLE education (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER NOT NULL,
    type_id INTEGER,
    start_date DATE,
    end_date DATE,
    url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE education ADD CONSTRAINT fk_education_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE education ADD CONSTRAINT fk_education_type FOREIGN KEY (type_id) REFERENCES education_types(id) ON DELETE SET NULL;

CREATE TABLE skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER NOT NULL,
    type_id INTEGER,
    created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE skills ADD CONSTRAINT fk_skills_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE skills ADD CONSTRAINT fk_skills_type FOREIGN KEY (type_id) REFERENCES skill_types(id) ON DELETE SET NULL;