/*
CREATE TABLE profiles_translations (
    id SERIAL PRIMARY KEY,
    profile_id INTEGER REFERENCES profiles(id) ON DELETE CASCADE,
    language_code CHAR(2) NOT NULL,
    location VARCHAR(150),
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(profile_id, language_code)
);

CREATE TABLE summaries_translations (
    id SERIAL PRIMARY KEY,
    summary_id INTEGER REFERENCES summaries(id) ON DELETE CASCADE,
    language_code CHAR(2) NOT NULL,
    label VARCHAR(100),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(summary_id, language_code)
);

CREATE TABLE experiences_translations (
    id SERIAL PRIMARY KEY,
    experience_id INTEGER REFERENCES experiences(id) ON DELETE CASCADE,
    language_code CHAR(2) NOT NULL,
    position VARCHAR(100) NOT NULL,
    location VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(experience_id, language_code)
);

CREATE TABLE responsibilities_translations (
    id SERIAL PRIMARY KEY,
    responsibility_id INTEGER REFERENCES responsibilities(id) ON DELETE CASCADE,
    language_code CHAR(2) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(responsibility_id, language_code)
);

CREATE TABLE education_translations (
    id SERIAL PRIMARY KEY,
    education_id INTEGER REFERENCES education(id) ON DELETE CASCADE,
    language_code CHAR(2) NOT NULL,
    title VARCHAR(150) NOT NULL,
    institution VARCHAR(150) NOT NULL,
    location VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(education_id, language_code)
);

CREATE TABLE skill_translations (
    id SERIAL PRIMARY KEY,
    skill_id INTEGER REFERENCES skills(id) ON DELETE CASCADE,
    language_code CHAR(2) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(skill_id, language_code)
);
*/

-- Tablas de Traducciones (Contenido literario)

-- Esquema de tabla única por entidad para mayor claridad

-- 1. PROFILES_TRANSLATIONS

CREATE TABLE profiles_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER NOT NULL,
    language_code CHAR(2) NOT NULL,
    location VARCHAR(150),
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX idx_profiles_trans_profile_lang ON profiles_translations(profile_id, language_code);
ALTER TABLE profiles_translations ADD CONSTRAINT fk_profiles_trans_profile 
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- 2. SUMMARIES_TRANSLATIONS

CREATE TABLE summaries_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary_id INTEGER NOT NULL,
    language_code CHAR(2) NOT NULL,
    label VARCHAR(100),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX idx_summaries_trans_summary_lang ON summaries_translations(summary_id, language_code);
ALTER TABLE summaries_translations ADD CONSTRAINT fk_summaries_trans_summary 
    FOREIGN KEY (summary_id) REFERENCES summaries(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- 3. EXPERIENCES_TRANSLATIONS

CREATE TABLE experiences_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experience_id INTEGER NOT NULL,
    language_code CHAR(2) NOT NULL,
    position VARCHAR(100) NOT NULL,
    location VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX idx_experiences_trans_exp_lang ON experiences_translations(experience_id, language_code);
ALTER TABLE experiences_translations ADD CONSTRAINT fk_experiences_trans_experience 
    FOREIGN KEY (experience_id) REFERENCES experiences(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- 4. RESPONSIBILITIES_TRANSLATIONS

CREATE TABLE responsibilities_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsibility_id INTEGER NOT NULL,
    language_code CHAR(2) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX idx_responsibilities_trans_resp_lang ON responsibilities_translations(responsibility_id, language_code);
ALTER TABLE responsibilities_translations ADD CONSTRAINT fk_responsibilities_trans_resp 
    FOREIGN KEY (responsibility_id) REFERENCES responsibilities(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- 5. EDUCATION_TRANSLATIONS

CREATE TABLE education_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_id INTEGER NOT NULL,
    language_code CHAR(2) NOT NULL,
    title VARCHAR(150) NOT NULL,
    institution VARCHAR(150) NOT NULL,
    location VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX idx_education_trans_edu_lang ON education_translations(education_id, language_code);
ALTER TABLE education_translations ADD CONSTRAINT fk_education_trans_education 
    FOREIGN KEY (education_id) REFERENCES education(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- 6. SKILL_TRANSLATIONS

CREATE TABLE skill_translations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id INTEGER NOT NULL,
    language_code CHAR(2) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX idx_skill_trans_skill_lang ON skill_translations(skill_id, language_code);
ALTER TABLE skill_translations ADD CONSTRAINT fk_skill_trans_skill 
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;