-- HABILITAR RLS EN TODAS LAS TABLAS

-- Sin esto, aunque la tabla exista, la API no dejará pasar datos si marcaste "Enable Automatic RLS"

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles_contact ENABLE ROW LEVEL SECURITY;
ALTER TABLE summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE responsibilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE education_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE education ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE summaries_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE experiences_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE responsibilities_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE education_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_translations ENABLE ROW LEVEL SECURITY;