BEGIN;

-- =============================================
-- 1. GRUPO: PERFIL Y CONTACTO
-- =============================================
ALTER TABLE profiles ALTER COLUMN id DROP DEFAULT;
ALTER TABLE profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE profiles_contact ALTER COLUMN id DROP DEFAULT;
ALTER TABLE profiles_contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Usamos DROP y ADD para evitar errores de nombres truncados
ALTER TABLE profiles_contact DROP CONSTRAINT IF EXISTS profiles_contact_email_key;
ALTER TABLE profiles_contact DROP CONSTRAINT IF EXISTS profiles_contact_profile_id_key;
CREATE UNIQUE INDEX idx_profiles_contact_email ON profiles_contact(email);
CREATE UNIQUE INDEX idx_profiles_contact_profile_id ON profiles_contact(profile_id);

ALTER TABLE profiles_contact DROP CONSTRAINT IF EXISTS profiles_contact_profile_id_fkey;
ALTER TABLE profiles_contact ADD CONSTRAINT fk_contact_profile 
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;


-- =============================================
-- 2. GRUPO: CONTENIDO PROFESIONAL
-- =============================================
ALTER TABLE summaries ALTER COLUMN id DROP DEFAULT;
ALTER TABLE summaries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE summaries DROP CONSTRAINT IF EXISTS summaries_profile_id_fkey;
ALTER TABLE summaries ADD CONSTRAINT fk_summaries_profile 
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE experiences ALTER COLUMN id DROP DEFAULT;
ALTER TABLE experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE experiences DROP CONSTRAINT IF EXISTS experiences_profile_id_fkey;
ALTER TABLE experiences ADD CONSTRAINT fk_experiences_profile 
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE responsibilities ALTER COLUMN id DROP DEFAULT;
ALTER TABLE responsibilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE responsibilities DROP CONSTRAINT IF EXISTS responsibilities_experience_id_fkey;
ALTER TABLE responsibilities ADD CONSTRAINT fk_responsibilities_experience 
    FOREIGN KEY (experience_id) REFERENCES experiences(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;


-- =============================================
-- 3. GRUPO: CLASIFICACIÓN Y EDUCACIÓN
-- =============================================
ALTER TABLE education_types ALTER COLUMN id DROP DEFAULT;
ALTER TABLE education_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE education_types DROP CONSTRAINT IF EXISTS education_types_slug_key;
CREATE UNIQUE INDEX idx_education_types_slug ON education_types(slug);

ALTER TABLE skill_types ALTER COLUMN id DROP DEFAULT;
ALTER TABLE skill_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE skill_types DROP CONSTRAINT IF EXISTS skill_types_slug_key;
CREATE UNIQUE INDEX idx_skill_types_slug ON skill_types(slug);

-- Education & Skills FKs
ALTER TABLE education ALTER COLUMN id DROP DEFAULT;
ALTER TABLE education ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE education DROP CONSTRAINT IF EXISTS education_profile_id_fkey;
ALTER TABLE education ADD CONSTRAINT fk_education_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE education DROP CONSTRAINT IF EXISTS education_type_id_fkey;
ALTER TABLE education ADD CONSTRAINT fk_education_type FOREIGN KEY (type_id) REFERENCES education_types(id) ON DELETE SET NULL;

ALTER TABLE skills ALTER COLUMN id DROP DEFAULT;
ALTER TABLE skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE skills DROP CONSTRAINT IF EXISTS skills_profile_id_fkey;
ALTER TABLE skills ADD CONSTRAINT fk_skills_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE skills DROP CONSTRAINT IF EXISTS skills_type_id_fkey;
ALTER TABLE skills ADD CONSTRAINT fk_skills_type FOREIGN KEY (type_id) REFERENCES skill_types(id) ON DELETE SET NULL;


-- =============================================
-- 4. GRUPO: TRADUCCIONES (Multi-idioma)
-- =============================================

-- Para las traducciones, eliminamos cualquier constraint UNIQUE previa y creamos el nuevo índice limpio.
-- Esto soluciona el error del nombre truncado definitivamente.

-- profiles_translations
ALTER TABLE profiles_translations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE profiles_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE profiles_translations DROP CONSTRAINT IF EXISTS profiles_translations_profile_id_language_code_key;
CREATE UNIQUE INDEX idx_profiles_trans_profile_lang ON profiles_translations(profile_id, language_code);
ALTER TABLE profiles_translations DROP CONSTRAINT IF EXISTS profiles_translations_profile_id_fkey;
ALTER TABLE profiles_translations ADD CONSTRAINT fk_profiles_trans_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- summaries_translations
ALTER TABLE summaries_translations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE summaries_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE summaries_translations DROP CONSTRAINT IF EXISTS summaries_translations_summary_id_language_code_key;
CREATE UNIQUE INDEX idx_summaries_trans_summary_lang ON summaries_translations(summary_id, language_code);
ALTER TABLE summaries_translations DROP CONSTRAINT IF EXISTS summaries_translations_summary_id_fkey;
ALTER TABLE summaries_translations ADD CONSTRAINT fk_summaries_trans_summary FOREIGN KEY (summary_id) REFERENCES summaries(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- experiences_translations
ALTER TABLE experiences_translations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE experiences_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE experiences_translations DROP CONSTRAINT IF EXISTS experiences_translations_experience_id_language_code_key;
CREATE UNIQUE INDEX idx_experiences_trans_exp_lang ON experiences_translations(experience_id, language_code);
ALTER TABLE experiences_translations DROP CONSTRAINT IF EXISTS experiences_translations_experience_id_fkey;
ALTER TABLE experiences_translations ADD CONSTRAINT fk_experiences_trans_experience FOREIGN KEY (experience_id) REFERENCES experiences(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- responsibilities_translations (EL DEL ERROR)
ALTER TABLE responsibilities_translations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE responsibilities_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- Aquí está el truco: usamos DROP CONSTRAINT IF EXISTS con el nombre largo (Postgres lo truncará solo para buscarlo)
ALTER TABLE responsibilities_translations DROP CONSTRAINT IF EXISTS responsibilities_translations_responsibility_id_language_code_key;
-- Y por si acaso el nombre en tu remote_schema.sql quedó distinto, intentamos también con el truncado manual
ALTER TABLE responsibilities_translations DROP CONSTRAINT IF EXISTS responsibilities_translations_responsibility_id_language_code_k;
CREATE UNIQUE INDEX idx_responsibilities_trans_resp_lang ON responsibilities_translations(responsibility_id, language_code);
ALTER TABLE responsibilities_translations DROP CONSTRAINT IF EXISTS responsibilities_translations_responsibility_id_fkey;
ALTER TABLE responsibilities_translations ADD CONSTRAINT fk_responsibilities_trans_resp FOREIGN KEY (responsibility_id) REFERENCES responsibilities(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- education_translations
ALTER TABLE education_translations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE education_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE education_translations DROP CONSTRAINT IF EXISTS education_translations_education_id_language_code_key;
CREATE UNIQUE INDEX idx_education_trans_edu_lang ON education_translations(education_id, language_code);
ALTER TABLE education_translations DROP CONSTRAINT IF EXISTS education_translations_education_id_fkey;
ALTER TABLE education_translations ADD CONSTRAINT fk_education_trans_education FOREIGN KEY (education_id) REFERENCES education(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- skill_translations
ALTER TABLE skill_translations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE skill_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE skill_translations DROP CONSTRAINT IF EXISTS skill_translations_skill_id_language_code_key;
CREATE UNIQUE INDEX idx_skill_trans_skill_lang ON skill_translations(skill_id, language_code);
ALTER TABLE skill_translations DROP CONSTRAINT IF EXISTS skill_translations_skill_id_fkey;
ALTER TABLE skill_translations ADD CONSTRAINT fk_skill_trans_skill FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

COMMIT;
